import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import { Helmet } from "react-helmet-async";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { getArticleBySlug, incrementArticleViews, getRecentArticles } from "@/db/api";
import type { ArticleWithAuthor } from "@/types";
import { ArrowLeft, Calendar, User, Eye, Clock, TrendingUp, Home, ChevronRight } from "lucide-react";
import { useRecordBrowsing } from "@/hooks/useRecordBrowsing";
import PageMeta from "@/components/common/PageMeta";

export default function ArticleDetail() {
  const { slug } = useParams<{ slug: string }>();
  const [article, setArticle] = useState<ArticleWithAuthor | null>(null);
  const [recentArticles, setRecentArticles] = useState<ArticleWithAuthor[]>([]);
  const [relatedArticles, setRelatedArticles] = useState<ArticleWithAuthor[]>([]);
  const [loading, setLoading] = useState(true);

  // Record browsing history
  useRecordBrowsing("article", article?.id, article?.title);

  useEffect(() => {
    if (slug) {
      Promise.all([
        getArticleBySlug(slug),
        getRecentArticles(5)
      ]).then(([articleData, recentData]) => {
        setArticle(articleData);
        setRecentArticles(recentData);
        
        if (articleData) {
          incrementArticleViews(articleData.id);
          
          // Get related articles (other articles in the same category)
          if (articleData.category) {
            getRecentArticles(6).then(allArticles => {
              const related = allArticles
                .filter(a => 
                  a.category?.id === articleData.category?.id && 
                  a.id !== articleData.id
                )
                .slice(0, 5);
              setRelatedArticles(related);
            });
          }
        }
        
        setLoading(false);
      }).catch(error => {
        console.error("Failed to load article:", error);
        setLoading(false);
      });
    }
  }, [slug]);

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
      </div>
    );
  }

  if (!article) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen gap-4">
        <h1 className="text-2xl font-bold">Article Not Found</h1>
        <Button asChild>
          <Link to="/articles">Back to Articles</Link>
        </Button>
      </div>
    );
  }

  return (
    <div className="min-h-screen py-8 xl:py-12 px-3 xl:px-4 bg-background">
      <PageMeta 
        title={article.title}
        type="article"
        autoGenerateDescription={true}
        contentForDescription={article.content || article.title}
        image={article.cover_image || undefined}
        author={article.author?.username || undefined}
        publishedTime={article.created_at}
        modifiedTime={article.updated_at}
      />
      
      {/* 结构化数据 - 面包屑导航 */}
      <Helmet>
        <script type="application/ld+json">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "BreadcrumbList",
            "itemListElement": [
              {
                "@type": "ListItem",
                "position": 1,
                "name": "Home",
                "item": window.location.origin
              },
              {
                "@type": "ListItem",
                "position": 2,
                "name": "Articles",
                "item": `${window.location.origin}/articles`
              },
              ...(article.category ? [{
                "@type": "ListItem",
                "position": 3,
                "name": article.category.name,
                "item": `${window.location.origin}/articles/category/${article.category.id}`
              }] : []),
              {
                "@type": "ListItem",
                "position": article.category ? 4 : 3,
                "name": article.title,
                "item": window.location.href
              }
            ]
          })}
        </script>
      </Helmet>
      
      <div className="container mx-auto max-w-7xl">
        {/* 面包屑导航 */}
        <nav className="flex items-center gap-2 text-sm text-muted-foreground mb-6" aria-label="Breadcrumb">
          <Link to="/" className="hover:text-foreground transition-colors flex items-center gap-1">
            <Home className="h-4 w-4" />
            Home
          </Link>
          <ChevronRight className="h-4 w-4" />
          <Link to="/articles" className="hover:text-foreground transition-colors">
            Articles
          </Link>
          {article.category && (
            <>
              <ChevronRight className="h-4 w-4" />
              <Link 
                to={`/articles/category/${article.category.id}`}
                className="hover:text-foreground transition-colors"
              >
                {article.category.name}
              </Link>
            </>
          )}
          <ChevronRight className="h-4 w-4" />
          <span className="text-foreground font-medium line-clamp-1">{article.title}</span>
        </nav>

        <div className="grid grid-cols-1 xl:grid-cols-12 gap-6 xl:gap-8">
          {/* Main Content */}
          <article className="xl:col-span-8">
            <Card>
              <CardHeader>
                {article.cover_image && (
                  <img
                    src={article.cover_image}
                    alt={article.title}
                    className="w-full h-64 xl:h-96 object-cover rounded-lg mb-6"
                    loading="lazy"
                    itemProp="image"
                  />
                )}
                <div className="flex flex-wrap items-center gap-2 xl:gap-3 mb-4">
                  {article.category && (
                    <Link to={`/articles/category/${article.category.id}`}>
                      <Badge variant="secondary" className="hover:bg-primary hover:text-primary-foreground transition-colors cursor-pointer text-xs xl:text-sm">
                        {article.category.name}
                      </Badge>
                    </Link>
                  )}
                  <div className="flex items-center gap-1 text-xs xl:text-sm text-muted-foreground">
                    <Calendar className="h-3 w-3 xl:h-4 xl:w-4" />
                    <time dateTime={article.created_at} itemProp="datePublished">
                      {new Date(article.created_at).toLocaleDateString('en-US', { 
                        year: 'numeric', 
                        month: 'short', 
                        day: 'numeric' 
                      })}
                    </time>
                  </div>
                  <div className="flex items-center gap-1 text-xs xl:text-sm text-muted-foreground">
                    <User className="h-3 w-3 xl:h-4 xl:w-4" />
                    <span itemProp="author">{article.author?.username || "Anonymous"}</span>
                  </div>
                  <div className="flex items-center gap-1 text-xs xl:text-sm text-muted-foreground">
                    <Eye className="h-3 w-3 xl:h-4 xl:w-4" />
                    {article.view_count} views
                  </div>
                </div>
                <CardTitle className="text-2xl xl:text-3xl" itemProp="headline">
                  <h1>{article.title}</h1>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div 
                  className="rich-content" 
                  itemProp="articleBody"
                  dangerouslySetInnerHTML={{ __html: article.content }} 
                />
              </CardContent>
            </Card>
          </article>

          {/* Sidebar */}
          <aside className="xl:col-span-4 space-y-6">
            {/* Author Info - Disabled */}
            {/* {article.author && (
              <Card>
                <CardHeader>
                  <CardTitle className="text-lg xl:text-xl flex items-center gap-2">
                    <User className="h-5 w-5" />
                    About Author
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  <div className="flex items-center gap-3">
                    {article.author.avatar_url ? (
                      <img 
                        src={article.author.avatar_url} 
                        alt={article.author.username || "Author"} 
                        className="h-12 w-12 rounded-full object-cover"
                      />
                    ) : (
                      <div className="h-12 w-12 rounded-full bg-primary/10 flex items-center justify-center">
                        <User className="h-6 w-6 text-primary" />
                      </div>
                    )}
                    <div>
                      <p className="font-semibold text-sm xl:text-base">{article.author.username || "Anonymous"}</p>
                      <p className="text-xs xl:text-sm text-muted-foreground">{article.author.email}</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            )} */}

            {/* Related Articles */}
            {relatedArticles.length > 0 && (
              <Card>
                <CardHeader>
                  <CardTitle className="text-lg xl:text-xl flex items-center gap-2">
                    <TrendingUp className="h-5 w-5" />
                    Related Articles
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  {relatedArticles.map((relatedArticle) => (
                    <Link 
                      key={relatedArticle.id} 
                      to={`/articles/${relatedArticle.slug}`}
                      className="block group"
                    >
                      <div className="space-y-1.5">
                        <h4 className="text-sm xl:text-base font-medium line-clamp-2 group-hover:text-primary transition-colors">
                          {relatedArticle.title}
                        </h4>
                        <div className="flex items-center gap-2 text-xs text-muted-foreground">
                          <span className="flex items-center gap-1">
                            <Eye className="h-3 w-3" />
                            {relatedArticle.view_count}
                          </span>
                          <span>•</span>
                          <span className="flex items-center gap-1">
                            <Clock className="h-3 w-3" />
                            {new Date(relatedArticle.created_at).toLocaleDateString('en-US', { 
                              month: 'short', 
                              day: 'numeric' 
                            })}
                          </span>
                        </div>
                      </div>
                      {relatedArticles.indexOf(relatedArticle) < relatedArticles.length - 1 && (
                        <Separator className="mt-3" />
                      )}
                    </Link>
                  ))}
                </CardContent>
              </Card>
            )}

            {/* Recent Articles */}
            {recentArticles.length > 0 && (
              <Card>
                <CardHeader>
                  <CardTitle className="text-lg xl:text-xl flex items-center gap-2">
                    <Clock className="h-5 w-5" />
                    Recent Articles
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  {recentArticles
                    .filter(a => a.id !== article.id)
                    .slice(0, 5)
                    .map((recentArticle) => (
                    <Link 
                      key={recentArticle.id} 
                      to={`/articles/${recentArticle.slug}`}
                      className="block group"
                    >
                      <div className="space-y-1.5">
                        <h4 className="text-sm xl:text-base font-medium line-clamp-2 group-hover:text-primary transition-colors">
                          {recentArticle.title}
                        </h4>
                        <div className="flex items-center gap-2 text-xs text-muted-foreground">
                          <span className="flex items-center gap-1">
                            <Eye className="h-3 w-3" />
                            {recentArticle.view_count}
                          </span>
                          <span>•</span>
                          <span className="flex items-center gap-1">
                            <Clock className="h-3 w-3" />
                            {new Date(recentArticle.created_at).toLocaleDateString('en-US', { 
                              month: 'short', 
                              day: 'numeric' 
                            })}
                          </span>
                        </div>
                      </div>
                      {recentArticles.filter(a => a.id !== article.id).indexOf(recentArticle) < 
                        Math.min(recentArticles.filter(a => a.id !== article.id).length - 1, 4) && (
                        <Separator className="mt-3" />
                      )}
                    </Link>
                  ))}
                </CardContent>
              </Card>
            )}

            {/* Call to Action */}
            <Card className="bg-gradient-to-br from-primary/10 via-primary/5 to-background border-primary/20">
              <CardContent className="pt-6 text-center space-y-3">
                <h3 className="text-lg font-semibold">Have Questions?</h3>
                <p className="text-sm text-muted-foreground">
                  Join our community and get answers from experts
                </p>
                <Button asChild className="w-full">
                  <Link to="/questions">Ask a Question</Link>
                </Button>
              </CardContent>
            </Card>
          </aside>
        </div>
      </div>
    </div>
  );
}
