import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import { Helmet } from "react-helmet-async";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { getProductBySlug, incrementProductViews } from "@/db/api";
import type { ProductWithImages } from "@/types";
import { ArrowLeft, Eye, Home, ChevronRight } from "lucide-react";
import { useRecordBrowsing } from "@/hooks/useRecordBrowsing";
import PageMeta from "@/components/common/PageMeta";

export default function ProductDetail() {
  const { slug } = useParams<{ slug: string }>();
  const [product, setProduct] = useState<ProductWithImages | null>(null);
  const [loading, setLoading] = useState(true);
  const [currentImage, setCurrentImage] = useState(0);

  // 记录浏览历史
  useRecordBrowsing("product", product?.id, product?.name);

  useEffect(() => {
    if (slug) {
      getProductBySlug(slug).then(data => {
        setProduct(data);
        if (data) incrementProductViews(data.id);
        setLoading(false);
      }).catch(error => {
        console.error("Failed to load products:", error);
        setLoading(false);
      });
    }
  }, [slug]);

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
      </div>
    );
  }

  if (!product) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen gap-4">
        <h1 className="text-2xl font-bold">Product not found</h1>
        <Button asChild>
          <Link to="/products">Back to Product List</Link>
        </Button>
      </div>
    );
  }

  return (
    <div className="min-h-screen py-8 xl:py-12 px-3 xl:px-4">
      <PageMeta 
        title={product.name}
        type="product"
        autoGenerateDescription={true}
        contentForDescription={product.description || product.name}
        image={product.images && product.images.length > 0 ? product.images[0].image_url : undefined}
      />
      
      {/* 结构化数据 - 面包屑导航 */}
      <Helmet>
        <script type="application/ld+json">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "BreadcrumbList",
            "itemListElement": [
              {
                "@type": "ListItem",
                "position": 1,
                "name": "Home",
                "item": window.location.origin
              },
              {
                "@type": "ListItem",
                "position": 2,
                "name": "Products",
                "item": `${window.location.origin}/products`
              },
              ...(product.category ? [{
                "@type": "ListItem",
                "position": 3,
                "name": product.category.name,
                "item": `${window.location.origin}/products/category/${product.category.id}`
              }] : []),
              {
                "@type": "ListItem",
                "position": product.category ? 4 : 3,
                "name": product.name,
                "item": window.location.href
              }
            ]
          })}
        </script>
        {/* 增强的Product结构化数据 */}
        <script type="application/ld+json">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "Product",
            "name": product.name,
            "description": product.description,
            "image": product.images?.map(img => img.image_url) || [],
            "brand": {
              "@type": "Brand",
              "name": "iFixes"
            },
            ...(product.price && {
              "offers": {
                "@type": "Offer",
                "price": product.price,
                "priceCurrency": "USD",
                "availability": "https://schema.org/InStock"
              }
            })
          })}
        </script>
      </Helmet>
      
      <div className="container mx-auto max-w-6xl">
        {/* 面包屑导航 */}
        <nav className="flex items-center gap-2 text-sm text-muted-foreground mb-6" aria-label="Breadcrumb">
          <Link to="/" className="hover:text-foreground transition-colors flex items-center gap-1">
            <Home className="h-4 w-4" />
            Home
          </Link>
          <ChevronRight className="h-4 w-4" />
          <Link to="/products" className="hover:text-foreground transition-colors">
            Products
          </Link>
          {product.category && (
            <>
              <ChevronRight className="h-4 w-4" />
              <Link 
                to={`/products/category/${product.category.id}`}
                className="hover:text-foreground transition-colors"
              >
                {product.category.name}
              </Link>
            </>
          )}
          <ChevronRight className="h-4 w-4" />
          <span className="text-foreground font-medium line-clamp-1">{product.name}</span>
        </nav>

        <div className="grid grid-cols-1 xl:grid-cols-2 gap-8">
          <div>
            {product.images && product.images.length > 0 && (
              <div className="space-y-4">
                <div className="aspect-square w-full overflow-hidden rounded-lg bg-muted">
                  <img
                    src={product.images[currentImage].image_url}
                    alt={product.name}
                    className="w-full h-full object-cover"
                    loading="lazy"
                    itemProp="image"
                  />
                </div>
                <div className="grid grid-cols-5 gap-2">
                  {product.images.map((img, idx) => (
                    <button
                      key={img.id}
                      onClick={() => setCurrentImage(idx)}
                      className={`border-2 rounded-lg overflow-hidden aspect-square ${
                        currentImage === idx ? "border-primary" : "border-border"
                      }`}
                      aria-label={`View image ${idx + 1}`}
                    >
                      <img
                        src={img.image_url}
                        alt={`${product.name} ${idx + 1}`}
                        className="w-full h-full object-cover"
                        loading="lazy"
                      />
                    </button>
                  ))}
                </div>
              </div>
            )}
          </div>

          <Card itemScope itemType="https://schema.org/Product">
            <CardHeader>
              <div className="flex items-center gap-2 mb-2">
                {product.category && (
                  <Link to={`/products/category/${product.category.id}`}>
                    <Badge variant="secondary" className="hover:bg-primary hover:text-primary-foreground transition-colors cursor-pointer">
                      {product.category.name}
                    </Badge>
                  </Link>
                )}
                <div className="flex items-center gap-1 text-sm text-muted-foreground">
                  <Eye className="h-4 w-4" />
                  {product.view_count} views
                </div>
              </div>
              <CardTitle className="text-3xl" itemProp="name">
                <h1>{product.name}</h1>
              </CardTitle>
              {product.price && (
                <div className="text-3xl font-bold text-primary mt-4" itemProp="offers" itemScope itemType="https://schema.org/Offer">
                  <meta itemProp="priceCurrency" content="USD" />
                  <span itemProp="price">${product.price}</span>
                </div>
              )}
            </CardHeader>
            <CardContent className="space-y-6">
              {product.description && (
                <div>
                  <h3 className="font-semibold text-lg mb-3">Product Description</h3>
                  <div 
                    className="rich-content text-muted-foreground"
                    itemProp="description"
                    dangerouslySetInnerHTML={{ __html: product.description }}
                  />
                </div>
              )}
            </CardContent>
          </Card>
        </div>

        {product.content && (
          <Card className="mt-8">
            <CardHeader>
              <CardTitle>Product Details</CardTitle>
            </CardHeader>
            <CardContent>
              <div 
                className="rich-content"
                dangerouslySetInnerHTML={{ __html: product.content }}
              />
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}
