import { Helmet } from "react-helmet-async";
import { useSEO } from "@/contexts/SEOContext";

interface PageMetaProps {
  title?: string;
  description?: string;
  keywords?: string;
  image?: string;
  type?: "website" | "article" | "product";
  author?: string;
  publishedTime?: string;
  modifiedTime?: string;
  autoGenerateDescription?: boolean;
  contentForDescription?: string;
}

/**
 * 页面级 SEO 组件（增强版）
 * 
 * 功能：
 * 1. 自动从全局 SEO 设置中获取网站名称
 * 2. 支持自定义页面标题、描述和关键词
 * 3. 自动从内容生成描述（提取前160个字符）
 * 4. 自动从标题和描述提取关键词
 * 5. 支持文章和产品的结构化数据
 * 6. 与后台管理设置实时同步
 * 
 * 使用方法：
 * 
 * 基础使用：
 * <PageMeta title="Articles" />
 * 
 * 自动生成描述：
 * <PageMeta 
 *   title="Product Name"
 *   autoGenerateDescription={true}
 *   contentForDescription={productDescription}
 * />
 * 
 * 完整配置：
 * <PageMeta 
 *   title="Article Title"
 *   description="Custom description"
 *   keywords="keyword1, keyword2"
 *   image="https://example.com/image.jpg"
 *   type="article"
 *   author="John Doe"
 *   publishedTime="2024-01-01"
 * />
 */
const PageMeta = ({ 
  title, 
  description, 
  keywords, 
  image,
  type = "website",
  author,
  publishedTime,
  modifiedTime,
  autoGenerateDescription = false,
  contentForDescription
}: PageMetaProps) => {
  const { settings } = useSEO();

  // 构建完整标题
  const fullTitle = title 
    ? `${title} - ${settings.siteName}` 
    : settings.siteName;

  // 自动生成描述：从内容中提取前160个字符
  const generateDescription = (content: string): string => {
    // 移除HTML标签
    const plainText = content.replace(/<[^>]*>/g, '');
    // 移除多余空白
    const cleaned = plainText.replace(/\s+/g, ' ').trim();
    // 截取前160个字符
    return cleaned.length > 160 
      ? cleaned.substring(0, 157) + '...' 
      : cleaned;
  };

  // 自动提取关键词：从标题和描述中提取
  const generateKeywords = (text: string): string => {
    // 移除HTML标签和特殊字符
    const cleaned = text.replace(/<[^>]*>/g, '').replace(/[^\w\s]/g, ' ');
    // 分词并过滤
    const words = cleaned.toLowerCase().split(/\s+/)
      .filter(word => word.length > 3) // 只保留长度大于3的词
      .filter((word, index, self) => self.indexOf(word) === index); // 去重
    // 取前10个词
    return words.slice(0, 10).join(', ');
  };

  // 确定最终的描述
  let metaDescription = description;
  if (!metaDescription && autoGenerateDescription && contentForDescription) {
    metaDescription = generateDescription(contentForDescription);
  }
  if (!metaDescription) {
    metaDescription = settings.siteDescription;
  }

  // 确定最终的关键词
  let metaKeywords = keywords;
  if (!metaKeywords && (title || metaDescription)) {
    const textForKeywords = `${title || ''} ${metaDescription || ''}`;
    metaKeywords = generateKeywords(textForKeywords);
  }
  if (!metaKeywords) {
    metaKeywords = settings.siteKeywords;
  }

  // 确定图片
  const metaImage = image || settings.siteLogo;

  return (
    <Helmet>
      <title>{fullTitle}</title>
      {metaDescription && <meta name="description" content={metaDescription} />}
      {metaKeywords && <meta name="keywords" content={metaKeywords} />}
      {author && <meta name="author" content={author} />}
      
      {/* Open Graph / Facebook */}
      <meta property="og:type" content={type} />
      <meta property="og:title" content={fullTitle} />
      {metaDescription && <meta property="og:description" content={metaDescription} />}
      {metaImage && <meta property="og:image" content={metaImage} />}
      <meta property="og:site_name" content={settings.siteName} />
      {publishedTime && <meta property="article:published_time" content={publishedTime} />}
      {modifiedTime && <meta property="article:modified_time" content={modifiedTime} />}
      {author && <meta property="article:author" content={author} />}
      
      {/* Twitter */}
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content={fullTitle} />
      {metaDescription && <meta name="twitter:description" content={metaDescription} />}
      {metaImage && <meta name="twitter:image" content={metaImage} />}
      
      {/* 结构化数据 - 文章 */}
      {type === "article" && (
        <script type="application/ld+json">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "Article",
            "headline": title,
            "description": metaDescription,
            "image": metaImage,
            "author": {
              "@type": "Person",
              "name": author || settings.siteName
            },
            "publisher": {
              "@type": "Organization",
              "name": settings.siteName,
              "logo": {
                "@type": "ImageObject",
                "url": settings.siteLogo
              }
            },
            "datePublished": publishedTime,
            "dateModified": modifiedTime || publishedTime
          })}
        </script>
      )}
      
      {/* 结构化数据 - 产品 */}
      {type === "product" && (
        <script type="application/ld+json">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "Product",
            "name": title,
            "description": metaDescription,
            "image": metaImage,
            "brand": {
              "@type": "Brand",
              "name": settings.siteName
            }
          })}
        </script>
      )}
    </Helmet>
  );
};

export default PageMeta;
